Repository KavyaGopal/Go-organic, pull requests merged in 2022-02, with the labels that each got.

#16 Updated missing module imports in navigation header component
  src/app/app.component.html
  src/app/app.module.ts
Labels: enhancement, sprint1

#17 [#15] Update: Bug Fix for missing user icon
  src/app/components/navigation-header/navigation-header.component.html
  src/assets/user_icon.svg
Labels: bug, sprint1

#22 Update: Bug fix done for mock api
  backend-go/pkg/api/api.go
Labels: bug, sprint1, user-story-1

#28 Frontend: fetchproduct details from backend
  angular.json
  backend-go/pkg/api/api.go
  backend-go/pkg/db/setupDB.go
  proxy.conf.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/get-api.service.spec.ts
  src/app/get-api.service.ts
Labels: sprint2

#32 Updated Json file according to "add elements to cart" functionality
  src/app/jsonData/fruits.json
  src/app/jsonData/groceries.json
  src/app/jsonData/snacks.json
  src/app/jsonData/vegetables.json
Labels: sprint2

#34 Sprint2 backend : Added API calls for all products
  backend-go/pkg/api/api.go
  backend-go/pkg/model/model.go
  src/app/components/home/home.component.ts
  src/app/get-api.service.ts
Labels: sprint2

#35 Sprint2 frontend backend integration
  src/app/app.component.ts
  src/app/components/home/home.component.ts
  src/app/get-api.service.ts
Labels: enhancement, sprint2
