Repository KavyaGopal/Go-organic, pull requests merged in 2022-03, with the labels that each got.

#39 Backend: DB update and fetch API calls done
  backend-go/pkg/api/api.go
  src/app/get-api.service.ts
Labels: sprint2

#37 Added routing to card and updated cart component and itemQuantity in DB
  backend-go/pkg/api/api.go
  src/app/components/cart/cart.component.css
  src/app/components/cart/cart.component.html
  src/app/components/cart/cart.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/navigation-header/navigation-header.component.html
Labels: sprint2

#41 #40 Cypress environment successfully setup
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/1-getting-started/todo.spec.js
  cypress/integration/2-advanced-examples/actions.spec.js
  cypress/integration/2-advanced-examples/aliasing.spec.js
  cypress/integration/2-advanced-examples/assertions.spec.js
  cypress/integration/2-advanced-examples/connectors.spec.js
  cypress/integration/2-advanced-examples/cookies.spec.js
  cypress/integration/2-advanced-examples/cypress_api.spec.js
  cypress/integration/2-advanced-examples/files.spec.js
  cypress/integration/2-advanced-examples/local_storage.spec.js
  cypress/integration/2-advanced-examples/location.spec.js
  cypress/integration/2-advanced-examples/misc.spec.js
  cypress/integration/2-advanced-examples/navigation.spec.js
  cypress/integration/2-advanced-examples/network_requests.spec.js
  cypress/integration/2-advanced-examples/querying.spec.js
  cypress/integration/2-advanced-examples/spies_stubs_clocks.spec.js
  cypress/integration/2-advanced-examples/traversal.spec.js
  cypress/integration/2-advanced-examples/utilities.spec.js
  cypress/integration/2-advanced-examples/viewport.spec.js
  cypress/integration/2-advanced-examples/waiting.spec.js
  cypress/integration/2-advanced-examples/window.spec.js
  cypress/integration/test-Components/cart/cart.specs.js
  cypress/integration/test-Components/dashboard/dashboard.specs.js
  cypress/integration/test-Components/home/home.specs.js
  cypress/integration/test-Components/navigation-header/navigation-header.specs.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  tsconfig.json
Labels: sprint2

#42 Zubin: Fix HomePage Slider View
  backend-go/ProductData.db
  backend-go/pkg/api/api.go
  backend-go/pkg/db/setupDB.go
  src/app/components/home/home.component.ts
Labels: sprint2

#48 #46 #47 Fontend component test:Home
  cypress/integration/1-getting-started/todo.spec.js
  cypress/integration/2-advanced-examples/actions.spec.js
  cypress/integration/2-advanced-examples/aliasing.spec.js
  cypress/integration/2-advanced-examples/assertions.spec.js
  cypress/integration/2-advanced-examples/connectors.spec.js
  cypress/integration/2-advanced-examples/cookies.spec.js
  cypress/integration/2-advanced-examples/cypress_api.spec.js
  cypress/integration/2-advanced-examples/files.spec.js
  cypress/integration/2-advanced-examples/local_storage.spec.js
  cypress/integration/2-advanced-examples/location.spec.js
  cypress/integration/2-advanced-examples/misc.spec.js
  cypress/integration/2-advanced-examples/navigation.spec.js
  cypress/integration/2-advanced-examples/network_requests.spec.js
  cypress/integration/2-advanced-examples/querying.spec.js
  cypress/integration/2-advanced-examples/spies_stubs_clocks.spec.js
  cypress/integration/2-advanced-examples/traversal.spec.js
  cypress/integration/2-advanced-examples/utilities.spec.js
  cypress/integration/2-advanced-examples/viewport.spec.js
  cypress/integration/2-advanced-examples/waiting.spec.js
  cypress/integration/2-advanced-examples/window.spec.js
  cypress/integration/test-Components/home/home.specs.js
Labels: bug, sprint2

#49 Added readme for sprint2
  sprint2.md
Labels: sprint2

#50 #33 Unit test for navigation header:Footer
  cypress/integration/test-Components/navigation-header/navigation-header.specs.js
Labels: sprint2

#54 Unit test to check the loading of dashboard component
  cypress/integration/test-Components/dashboard/dashboard.specs.js
Labels: sprint2

#55 Added unit test to check elements in cart component
  cypress/integration/test-Components/cart/cart.specs.js
Labels: sprint2

#69 Update: CORS Post Request Signup Resolved
  backend-go/go.mod
  backend-go/go.sum
  backend-go/pkg/api/ProductData.db
  backend-go/pkg/api/api.go
Labels: bug, sprint3

#70 Update: Done Encrypted Password for Signup-Login Zubin
  backend-go/go.mod
  backend-go/pkg/api/ProductData.db
  backend-go/pkg/api/api.go
Labels: sprint3

#71 [Sign Up][Front end]Updated json for communication with API
  src/app/components/sign-up/sign-up.component.html
  src/app/components/sign-up/sign-up.component.ts
Labels: sprint3

#72 Update: Phone type to string resolved for signup-login
  backend-go/pkg/model/model.go
Labels: bug, sprint3

#74 [#68]Integration: Sign in integration with backend api
  backend-go/pkg/api/ProductData.db
  src/app/components/login/login.component.ts
Labels: sprint3

#77 Update: Resolved bugfix for checkoutcomponent
  src/app/app.module.ts
Labels: bug, sprint3

#78 Update: Login Response API Updated Zubin
  backend-go/pkg/api/api.go
  backend-go/pkg/model/model.go
Labels: sprint3, user-story
