Repository KavyaGopal/Go-organic, pull requests merged in 2022-04, with the labels that each got.

#79 Bug Fixes
  backend-go/pkg/api/ProductData.db
  src/app/components/login/login.component.ts
  src/app/components/navigation-header/navigation-header.component.html
  src/app/components/navigation-header/navigation-header.component.ts
  src/app/components/sign-up/sign-up.component.html
  src/app/components/sign-up/sign-up.component.ts
  src/app/services/custom-validation.service.spec.ts
  src/app/services/custom-validation.service.ts
Labels: sprint3

#82 Fixed the bugs in Cart component
  src/app/components/cart/cart.component.css
  src/app/components/cart/cart.component.html
  src/app/components/cart/cart.component.ts
Labels: sprint3

#84 #83 Fixed the issues in the checkout component
  src/app/components/checkout/checkout.component.html
Labels: bug, sprint3

#87 #86 Added tests for checkout component and for routing connection
  cypress/integration/test-Components/cart/cart.specs.js
  cypress/integration/test-Components/checkout/checkout.specs.js
  cypress/integration/test-Components/home/home.specs.js
  cypress/screenshots/test-Components/cart/cart.specs.js/Tests Cart Component -- Checks if the cart has following elements (failed).png
  cypress/screenshots/test-Components/cart/cart.specs.js/Tests Cart Component -- Visits the Go organic Cart Component (failed).png
  cypress/screenshots/test-Components/dashboard/dashboard.specs.js/Tests dashboard Component -- Checks for the fields in dashoard component (failed).png
  cypress/screenshots/test-Components/dashboard/dashboard.specs.js/Tests dashboard Component -- Visits the Go organic Dashboard Component (failed).png
  cypress/screenshots/test-Components/home/home.specs.js/Tests home Component -- Check if Shop Now button is clickable (failed).png
  cypress/screenshots/test-Components/home/home.specs.js/Tests home Component -- Checks the category Fruits (failed).png
  cypress/screenshots/test-Components/home/home.specs.js/Tests home Component -- Checks the category Groceries (failed).png
  cypress/screenshots/test-Components/home/home.specs.js/Tests home Component -- Checks the category Snacks (failed).png
  cypress/screenshots/test-Components/home/home.specs.js/Tests home Component -- Checks the category Vegetables (failed).png
  cypress/screenshots/test-Components/home/home.specs.js/Tests home Component -- Visits the Go organic Home Component (failed).png
  cypress/screenshots/test-Components/navigation-header/navigation-header.specs.js/Tests navigation-header Component -- Checks the footer of navigation header (failed).png
  cypress/screenshots/test-Components/navigation-header/navigation-header.specs.js/Tests navigation-header Component -- Visits the Go organic Navigation-Header Component (failed).png
  src/app/components/checkout/checkout.component.html
Labels: bug, sprint3

#88 Sprint3 backend cart checkout
  backend-go/pkg/api/ProductData.db
  backend-go/pkg/api/api.go
  backend-go/pkg/db/setupDB.go
  backend-go/pkg/model/model.go
Labels: sprint3, user-story

#91 Sprint3 backend unit tests
  .gitignore
  backend-go/pkg/api/ProductData.db
  backend-go/pkg/api/api.go
  backend-go/pkg/api/api_test.go
Labels: sprint3, user-story

#92 Update: Progress and Video demos added for Sprint3 Zubin
  README.md
  sprint3.md
Labels: documentation

#95 backend : testimonial api setup done
  backend-go/pkg/api/ProductData.db
  backend-go/pkg/api/api.go
  backend-go/pkg/db/setupDB.go
  backend-go/pkg/model/model.go
  src/assets/testimonial-images/img-fm1.jpeg
  src/assets/testimonial-images/img-fm2.jpeg
  src/assets/testimonial-images/img-fm3.jpeg
  src/assets/testimonial-images/img-m1.png
  src/assets/testimonial-images/img-m2.jpeg
  src/assets/testimonial-images/img-m3.jpeg
Labels: user-story, sprint4

#97 Sprint4 backend reset password api
  .gitignore
  backend-go/pkg/api/ProductData.db
  backend-go/pkg/api/api.go
Labels: user-story, sprint4

#99 Update: Bugfix Re-adding db file
  backend-go/pkg/api/ProductData.db
Labels: bug

#100 Sprint4 backend payment api
  backend-go/go.mod
  backend-go/go.sum
  backend-go/pkg/api/.env
  backend-go/pkg/api/ProductData.db
  backend-go/pkg/api/api.go
  backend-go/pkg/db/setupDB.go
  backend-go/pkg/model/model.go
  backend-go/pkg/utils/utils.go
Labels: user-story, sprint4

#101 Bugfix: Testimonial Model Updated Zubin
  backend-go/pkg/api/ProductData.db
Labels: bug, sprint4

#102 Bug: Updated Testimonial Model Zubin
  backend-go/pkg/db/setupDB.go
  backend-go/pkg/model/model.go
Labels: bug, sprint4

#106 [Front End]Bug Fixes
  src/app/components/cart/cart.component.html
  src/app/components/cart/cart.component.ts
  src/assets/home_banner.png
Labels: sprint4

#107 [Front-end]Added Logout functionality
  backend-go/pkg/api/ProductData.db
  src/app/components/navigation-header/navigation-header.component.html
  src/app/components/navigation-header/navigation-header.component.ts
Labels: sprint4

#108 Added payment successful page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/payment/payment.component.css
  src/app/components/payment/payment.component.html
  src/app/components/payment/payment.component.spec.ts
  src/app/components/payment/payment.component.ts
Labels: sprint4

#109 Navigate to components(groceries, cosmetics and all) on clicking navigation bar
  src/app/components/home/home.component.html
  src/app/components/navigation-header/navigation-header.component.html
  src/app/components/navigation-header/navigation-header.component.ts
Labels: sprint4

#110 Update: Item Inventory Changes Fix Zubin
  backend-go/pkg/api/ProductData.db
  backend-go/pkg/api/api.go
  backend-go/pkg/db/setupDB.go
Labels: bug, sprint4

#111 Sprint4 frontend PayPal Payment
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/checkout/checkout.component.html
  src/app/components/paypalpayment/paypalpayment.component.css
  src/app/components/paypalpayment/paypalpayment.component.html
  src/app/components/paypalpayment/paypalpayment.component.spec.ts
  src/app/components/paypalpayment/paypalpayment.component.ts
  src/index.html
Labels: user-story, sprint4

#114 Sprint4 : backend unit tests
  backend-go/pkg/api/api.go
  backend-go/pkg/api/api_test.go
Labels: user-story, sprint4

#117 Updated description of products and fixed styling
  backend-go/pkg/api/ProductData.db
  src/app/components/home/home.component.css
Labels: sprint4

#112 BugFix: PayPal component not loading on route
  src/app/components/checkout/checkout.component.html
  src/app/components/checkout/checkout.component.ts
Labels: bug, user-story, sprint4

#118 Updated readme based on sprint 4 requirements
  README.md
Labels: sprint4

#113 BugFix: Added routing to payment successful message
  src/app/components/checkout/checkout.component.html
  src/app/components/checkout/checkout.component.ts
  src/app/components/paypalpayment/paypalpayment.component.html
  src/app/components/paypalpayment/paypalpayment.component.ts
Labels: bug, user-story, sprint4

#120 [#122][Frontend-backend integration]payment
  src/app/components/cart/cart.component.ts
  src/app/components/home/home.component.ts
  src/app/components/navigation-header/navigation-header.component.ts
  src/app/components/paypalpayment/paypalpayment.component.ts
  src/app/get-api.service.ts
  src/index.html
Labels: sprint4

#129 Added cypress tests for paypalpayment component
  cypress/integration/test-Components/paypalpayment/paypalpayment.specs.js
Labels: user-story, sprint4

#130 Updated payment completion component
  src/app/components/checkout/checkout.component.html
  src/app/components/payment/payment.component.ts
  src/app/components/paypalpayment/paypalpayment.component.ts
Labels: bug, sprint4

#131 Sprint4: backend update readme
  README.md
  sprint4.md
Labels: documentation, sprint4
